// File generated by FlutterFire CLI — values filled from platform config files.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platform is not configured. Run flutterfire configure for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFTjY62m_wEv5Lmt6nyqTHVyhWdT_DyY',
    appId: '1:33831460843:android:8d82faa9059f5ea53e03ae',
    messagingSenderId: '33831460843',
    projectId: 'collabhub-33a9d',
    storageBucket: 'collabhub-33a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFn-6BDVnpUQrU61Ytxl6Dm4TmoEddho',
    appId: '1:33831460843:ios:690ee679c42b84793e03ae',
    messagingSenderId: '33831460843',
    projectId: 'collabhub-33a9d',
    storageBucket: 'collabhub-33a9d.firebasestorage.app',
    iosBundleId: 'com.team11.collabhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFn-6BDVnpUQrU61Ytxl6Dm4TmoEddho',
    appId: '1:33831460843:ios:690ee679c42b84793e03ae',
    messagingSenderId: '33831460843',
    projectId: 'collabhub-33a9d',
    storageBucket: 'collabhub-33a9d.firebasestorage.app',
    iosBundleId: 'com.team11.collabhub',
  );
}
