// ── FIREBASE CONFIGURATION REQUIRED ──────────────────────────────────────────
//
// This file must be generated by the FlutterFire CLI before the app will run.
//
// Steps:
//   1. Create a project at https://console.firebase.google.com
//      - Enable Authentication (Email/Password + Google)
//      - Create a Firestore database (start in test mode, then lock down rules)
//   2. Install the CLI:
//        dart pub global activate flutterfire_cli
//   3. From the project root, run:
//        flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//   4. Select the platforms you target (iOS, Android, macOS …)
//   5. The CLI will overwrite this file with real values and update the
//      platform-specific configs (GoogleService-Info.plist, google-services.json)
//
// Firestore security rules (paste in the Firebase console):
//
//   rules_version = '2';
//   service cloud.firestore {
//     match /databases/{database}/documents {
//       match /users/{userId} {
//         allow read: if request.auth != null;
//         allow write: if request.auth.uid == userId;
//       }
//       match /projects/{projectId} {
//         allow read:   if request.auth != null;
//         allow create: if request.auth != null;
//         allow update: if request.auth != null;
//         allow delete: if request.auth.uid == resource.data.authorId;
//       }
//     }
//   }
//
// macOS extra step — open macos/Runner/DebugProfile.entitlements AND
// macos/Runner/Release.entitlements and add:
//   <key>com.apple.security.network.client</key><true/>
//
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder — replaced automatically when you run `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        return _macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.\n'
          'Run `flutterfire configure` to generate the correct options.',
        );
    }
  }

  // ── Replace the values below with your Firebase project's config ────────────
  // You can find them in the Firebase console under Project Settings > Your apps.

  static const _web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const _android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const _ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  static const _macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );
}
